### ISSUE TITLE
[ENHANCEMENT] Configure bucket that are automatically created

### ISSUE THREAD

**Issue by xItsSky** [xItsSky/minio-spring-boot-starter#3]
# Configure bucket that are automatically created

## Issue type
- [ ] Major Enhancement with Breaking changes
- [x] Major Enhancement without Breaking changes
- [ ] Minor Enhancement

## Current behavior
Currently we can only define bucket name in the configuration. There is no way to provide addition configuration to apply to the bucket that has to be auto created.

## Expected behavior
It could be useful if we are able to provide configuration (such as retention, policies ...) in the configuration, in order to apply directly this configuration to the bucket that will be created

Something like this:
```yaml
  ...
  buckets:
    - name: mybucket
      retention:
        ...
      policies:
        ...
```

## Any comments
/
